---
version: '3.3'
services:
    db:
        image: mysql
        restart: always
        healthcheck:
            test: exit 0
        environment:
            MYSQL_DATABASE: ${DB_NAME}
      # So you don't have to use root, but you can if you like
            MYSQL_USER: ${DB_USER}
      # You can use whatever password you like
            MYSQL_PASSWORD: ${DB_PASSWORD}
      # Password for root access
            MYSQL_ROOT_PASSWORD: password
        ports:
      # <Port exposed> : <MySQL Port running inside container>
            - 3306:3306
        expose:
      # Opens port 3306 on the container
            - '3306'
      # Where our data will be persisted
        volumes:
            - my-db:/var/lib/mysql

    api:
        # image: ghcr.io/kilianp07/muscleapp:latest
        build:
            context: .
            dockerfile: Dockerfile
        depends_on:
            db:
                condition: service_healthy
        ports:
            - 8080:8080
        environment:
            - DB_NAME=${DB_NAME}
            - DB_USER=${DB_USER}
            - DB_PASSWORD=${DB_PASSWORD}
            - DB_HOST=${DB_HOST}
            - DB_PORT=${DB_PORT}
            - SECRET_KEY=${SECRET_KEY}
            - API_PORT=${API_PORT}
# Names our volume
volumes:
    my-db:
